feat: adding pull request template
BerkeleyLearnVerify/Scenic pull request #219
Opened 2024-03-07 19:17 UTC by abanuelo

The goal of this PR is to introduce a way to format PR's by allowing users to:

1. Link back to existing issue that trickled the need for the PR
2. Relevant JIRA tickets (as needed)
3. Descriptions
4. PR Checklist satisfying that formatting, testing, and relevant documentation has been included in the PR

2024-03-12 21:32 UTC, dfremont commented on .github/workflows/PULL_REQUEST_TEMPLATE.md
> +- [ ] I have auto formatted the code to black and istio conventions
```suggestion
- [ ] I have autoformatted the code with black and isort
```

2024-03-12 21:32 UTC, dfremont requested changes
Looks great, just one tiny comment above.

2024-03-12 22:28 UTC, abanuelo commented on .github/workflows/PULL_REQUEST_TEMPLATE.md
> +- [ ] I have auto formatted the code to black and istio conventions
Ack!

2024-03-12 22:51 UTC, Eric-Vin approved these changes
Looks good to me!

2024-03-13 22:10 UTC, dfremont commented
SCENIC-12

2024-03-13 22:12 UTC, dfremont commented
[SCENIC-12]

2024-03-13 22:36 UTC, dfremont approved these changes

2024-03-13 22:36 UTC, merged