Requirement Boolean Negation Fix
BerkeleyLearnVerify/Scenic pull request #289
Opened 2024-07-10 13:19 UTC by Eric-Vin

### Description
Fixes an issue where `not` inside a requirement is not handled correctly.

### Issue Link
https://github.com/BerkeleyLearnVerify/Scenic/issues/286

### Checklist
- [X] I have tested the changes locally via `pytest` and/or other means
- [X] I have added or updated relevant documentation
- [X] I have autoformatted the code with black and isort
- [X] I have added test cases (if applicable)

### Additional Notes
N/A

2024-07-10 19:12 UTC, abanuelo approved these changes
Looks great to me!

2024-07-10 21:27 UTC, dfremont commented on src/scenic/syntax/compiler.py
> +        self.in_atomic = False
```suggestion
        self.inAtomic = False
```
(for consistency with the rest of this file and most of Scenic)

2024-07-10 21:28 UTC, dfremont requested changes
Looks great, just one stylistic nit.

2024-07-11 21:42 UTC, dfremont approved these changes

2024-07-11 21:43 UTC, merged